---

# For use with pre-commit.
# See usage instructions at https://pre-commit.com

- id: yamllint
  name: yamllint
  description: This hook runs yamllint.
  entry: yamllint
  language: python
  types: [file, yaml]
